name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
           choco install -y python --version=3.8.10
          
      - name: Install via official installer (fallback)
        shell: cmd
        run: |
          pip install --upgrade pip setuptools wheel
          pip uninstall -y PyQt5 PyQtWebEngine PyQt5-sip
          pip install PyQt5==5.15.4 PyQtWebEngine==5.15.5 --no-binary PyQt5,PyQtWebEngine
          dir C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\PyQt5\Qt"

