name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
        # 1. Полная переустановка PyQt5 с правильными зависимостями
      - name: Reinstall PyQt5 properly
        shell: cmd
        run: |
            pip uninstall -y PyQt5 PyQt5-sip PyQtWebEngine
            pip install --no-cache-dir --force-reinstall PyQt5==5.15.4 PyQtWebEngine==5.15.5
            python -c "import PyQt5, os; print('Qt dir exists:', os.path.exists(os.path.join(os.path.dirname(PyQt5.__file__), 'Qt')))"

  # 2. Проверка структуры Qt
      - name: Verify Qt structure
        shell: cmd
        run: |
           python -c """
           import os, PyQt5
           qt_dir = os.path.join(os.path.dirname(PyQt5.__file__), 'Qt')
           print('Qt directory:', qt_dir)
           if os.path.exists(qt_dir):
               print('Subdirectories:', [d for d in os.listdir(qt_dir) if os.path.isdir(os.path.join(qt_dir, d))])
           else:
               print('Qt directory not found!')
           """


