name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        shell: cmd
        run: |
          pip install --upgrade nuitka
          pip install PyQt5 PyQtWebEngine
          choco install innosetup -y
          choco install upx -y

      - name: Get Python and Qt paths
        id: get_paths
        shell: cmd
        run: |
          python -c "import sys; print(f'PYTHON_DIR={sys.prefix}')" >> %GITHUB_OUTPUT%
          python -c "import PyQt5, os; print(f'QT_DIR={os.path.dirname(PyQt5.__file__)}')" >> %GITHUB_OUTPUT%
          # Находим реальный путь к Qt
          python -c "import os, PyQt5; qt_dir = os.path.dirname(PyQt5.__file__); print(f'QT_DIR={qt_dir}')" >> %GITHUB_ENV%
      - name: Check disk space
        run: df -h 
      - name: List running processes
        run: tasklist
        
      - name: Compile with Nuitka
        shell: cmd
        run: |
          python -c "import os, PyQt5; qt_dir = os.path.join(os.path.dirname(PyQt5.__file__), 'Qt'); print(f'Qt bin exists: {os.path.exists(os.path.join(qt_dir, \"bin\"))}'); print(f'QtWebEngineProcess exists: {os.path.exists(os.path.join(qt_dir, \"bin\", \"QtWebEngineProcess.exe\"))}')"
          set QT_PATH=%{{ steps.get_paths.outputs.QT_DIR }}\Qt
          set DEST_DIR=PyQt5\Qt
          rmdir /s /q build 2>nul || true
          rmdir /s /q dist 2>nul || true
    
          # Запуск Nuitka с явным указанием временного каталога
          set TEMP=%GITHUB_WORKSPACE%\temp
          mkdir %TEMP%
          python -m nuitka ^
          --standalone ^
          --onefile ^
          --windows-console-mode=disable ^
          --output-dir=dist ^
          --enable-plugin=pyqt5 ^
          --windows-icon-from-ico=youunlock.ico ^
          --include-package=PyQt5.QtWebEngineWidgets ^
          --include-package=PyQt5.QtWebEngineCore ^
          --include-data-dir=%QT_DIR%\Qt\plugins=PyQt5/Qt/plugins ^
          --include-data-dir=%QT_DIR%\Qt\resources=PyQt5/Qt/resources ^
          --include-data-file=%QT_DIR%\Qt\bin\QtWebEngineProcess.exe=PyQt5/Qt/bin/ ^
          --assume-yes-for-downloads ^
          --noinclude-pytest-mode=nofollow ^
          --noinclude-setuptools-mode=nofollow ^
          --enable-plugin=upx ^
          --nofollow-import-to=unnecessary_module ^
          --jobs=2 ^
          --lto=yes ^
          --show-scons --show-progress ^
          unlock.py

      - name: Verify build
        shell: cmd
        run: |
          if exist dist\unlock.exe (
            echo "Build successful!"
            dir dist
          ) else (
            echo "Build failed!"
            exit 1
          )

      - name: Create installer script
        shell: cmd  # Важно использовать cmd вместо powershell
        run: |
          (
            echo [Setup]
            echo AppName=Youtubedpi
            echo AppVersion=1.0.1
            echo SetupIconFile=youunlock.ico
            echo DefaultDirName={pf}\Youtubedpi
            echo DefaultGroupName=Youtubedpi
            echo OutputDir=installer
            echo OutputBaseFilename=Youtube-app-with-nodpi-setup-1.0.1
            echo Compression=lzma
            echo SolidCompression=yes
            echo.
            echo [Files]
            echo Source: "dist\unlock.exe"; DestDir: "{app}"; Flags: ignoreversion
            echo Source: "blacklist.txt"; DestDir: "{app}"
            echo Source: "youtube.png"; DestDir: "{app}"
            echo.
            echo [Icons]
            echo Name: "{group}\Youtubedpi"; Filename: "{app}\unlock.exe"
          ) > installer.iss
      - name: Build installer
        shell: cmd  # Ключевое исправление - используем cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
      
      - name: Verify installer script
        shell: cmd
        run: |
          type installer.iss

      - name: Verify build
        shell: cmd
        run: |
          if exist installer\Youtube-app-with-nodpi-setup-1.0.1.exe (
            echo "Build successful!"
            dir dist
          ) else (
            echo "Build failed!"
            exit 1
          )
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\

      - name: Upload artifact 2
        uses: actions/upload-artifact@v4
        with:
          name: Youtube-app-with-nodpi-setup-1.0.1
          path: installer\

