
name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        shell: cmd
        run: |
          pip install --upgrade nuitka
          pip install PyQt5 PyQtWebEngine

      - name: Verify Qt installation
        shell: cmd
        run: |
          python -c "from PyQt5.QtWebEngineWidgets import QWebEngineView; print('QtWebEngine available')"
          python -c "import os, PyQt5; print('Qt bin path:', os.path.join(os.path.dirname(PyQt5.__file__), 'Qt', 'bin'))"

      - name: Compile with Nuitka
        shell: cmd
        run: |
          python -m nuitka ^
          --standalone ^
          --onefile ^
          --windows-console-mode=disable ^
          --output-dir=dist ^
          --enable-plugin=pyqt5 ^
          --windows-icon-from-ico=youunlock.ico ^
          --include-qt-plugins=webengine ^
          --include-data-dir=%PYTHONPATH%\Lib\site-packages\PyQt5\Qt\bin=PyQt5/Qt/bin ^
          --include-data-dir=%PYTHONPATH%\Lib\site-packages\PyQt5\Qt\resources=PyQt5/Qt/resources ^
          --include-data-dir=%PYTHONPATH%\Lib\site-packages\PyQt5\Qt\translations=PyQt5/Qt/translations ^
          --assume-yes-for-downloads ^
          unlock.py

      - name: Verify build
        shell: cmd
        run: |
          if exist dist\unlock.exe (
            echo "Build successful! File info:"
            dir dist\unlock.exe
          ) else (
            echo "Build failed!"
            exit 1
          )

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\unlock.exe