name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        shell: cmd
        run: |
          pip install --upgrade nuitka
          # Удаляем проблемные версии
          pip uninstall -y PyQt5 PyQtWebEngine PyQt5-sip PyQt5-tools
          # Ставим конкретные проверенные версии
          pip install PyQt5==5.15.4 PyQtWebEngine==5.15.5
          # Проверяем установку Qt
          python -c "import os, PyQt5; qt_dir = os.path.join(os.path.dirname(PyQt5.__file__), 'Qt'); assert os.path.exists(os.path.join(qt_dir, 'bin')), 'Qt bin folder missing!'; print('Qt found at:', qt_dir)"
          choco install innosetup -y
          choco install upx -y


        
      - name: Inspect PyQt5 directories
        shell: cmd
        run: |
          python -c "import PyQt5, os; print(f'PyQt5 location: {os.path.dirname(PyQt5.__file__)}')"
          tree "%PYTHONPATH%\Lib\site-packages\PyQt5" /F

