name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
           choco install -y python --version=3.8.10
           choco install -y qt5 --version=5.15.2
           refreshenv
          
      - name: Install via official installer (fallback)
        shell: cmd
        run: |
          pip install PyQt5 --install-option="--verbose" --install-option="--confirm-license"
          dir "%PYTHONPATH%\Lib\site-packages\PyQt5\Qt"
          pip install --upgrade pip setuptools wheel
          pip install PyQt5==5.15.4 ^
            --config-settings="--qmake=C:\Qt\5.15.2\msvc2019_64\bin\qmake.exe" ^
            --config-settings="--verbose"
          pip install PyQtWebEngine==5.15.5 ^
            --config-settings="--qmake=C:\Qt\5.15.2\msvc2019_64\bin\qmake.exe"
          dir "%PYTHONPATH%\Lib\site-packages\PyQt5\Qt"

