name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]  # Триггер на пуш в main
  pull_request:         # Опционально
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest  # Сборка под Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Укажите нужную версию Python

      - name: Install Nuitka
        run: pip install nuitka

      - name: Install additional dependencies (если нужны)
        run: |
          pip install pyqt5  # используется PyQt5
          pip install pyqtwebengine # pyqtwebengine используется

      - name: Compile with Nuitka (Standalone)
        shell: cmd
        run: python -m nuitka --standalone --onefile --windows-disable-console --output-dir=dist --enable-plugin=pyqt5 --include-qt-plugins=sensible,multimedia,webenginecore --windows-icon-from-ico=youunlock.ico unlock.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/