name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        run: |
           choco install -y python --version=3.8.10
          
      - name: Install via official installer (fallback)
        shell: cmd
        run: |
          pip install --upgrade pip setuptools wheel
          pip install PyQt5==5.15.4 PyQtWebEngine==5.15.5 ^
          --index-url https://pypi.ngc.nvidia.com ^
          --extra-index-url https://pypi.org/simple
          pip install PyQtWebEngine==5.15.5 ^
          --config-settings="--qmake=C:\Qt\5.15.2\msvc2019_64\bin\qmake.exe"
          dir C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\PyQt5\Qt"

