name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        shell: cmd
        run: |
          pip install nuitka
          pip install PyQt5 PyQtWebEngine

      - name: Compile with Nuitka
        shell: cmd
        run: |
          python -c "import PyQt5.QtCore; print('Qt path:', PyQt5.QtCore.QLibraryInfo.location(PyQt5.QtCore.QLibraryInfo.PrefixPath))"
          
          python -m nuitka ^
          --standalone ^
          --onefile ^
          --windows-console-mode=disable ^
          --output-dir=dist ^
          --enable-plugin=pyqt5 ^
          --windows-icon-from-ico=youunlock.ico ^
          --include-package=PyQt5.QtWebEngineWidgets ^
          --include-package=PyQt5.QtWebEngineCore ^
          --assume-yes-for-downloads ^  # Автоматическое подтверждение всех загрузок
          unlock.py
      - name: Verify build
        shell: cmd
        run: |
          if exist dist\unlock.exe (
            echo "Build successful!"
            dir dist
          ) else (
            echo "Build failed!"
            exit 1
          )

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\