name: Build Windows with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Установка Python 3.8 (более стабильная версия для PyQt5)
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install via official installer (fallback)
        shell: cmd
        run: |
          pip install --upgrade pip setuptools wheel
          pip uninstall -y PyQt5 PyQtWebEngine PyQt5-sip
          pip install PyQt5 PyQt5-Qt5 PyQtWebEngine
          dir C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\PyQt5\Qt5
          
      - name: Check PyQtWebEngine location
        run: |
          python -c "
            try:
                import PyQtWebEngine
                from pathlib import Path
            
                pyqtwebengine_path = Path(PyQtWebEngine.__file__).parent
                print('PyQtWebEngine location:', pyqtwebengine_path)
            
            print('\nDirectory structure:')
            for file in pyqtwebengine_path.rglob('*'):
                print(file)
            except Exception as e:
                print('Error:', e)
                raise
            "