
name: Find QtWebEngineProcess

on: [push, workflow_dispatch]

jobs:
  locate-webengine:
    runs-on: windows-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install via official installer (fallback)
      shell: cmd
      run: |
        pip install --upgrade pip setuptools wheel
        pip uninstall -y PyQt5 PyQtWebEngine PyQt5-sip
         pip install PyQt5 PyQt5-Qt5 PyQtWebEngine

    - name: Locate qtwebengineprocess.exe
      shell: pwsh
      run: |
        $output = python -c "
        import sys
        sys.stdout.reconfigure(encoding='utf-8')
        
        from PyQt5.QtCore import QLibraryInfo
        from PyQt5.QtWebEngineCore import QWebEngineProfile
        import os
        
        # Основной путь
        bin_path = QLibraryInfo.location(QLibraryInfo.BinariesPath)
        webengine_path = os.path.join(bin_path, 'qtwebengineprocess.exe')
        print('Основной путь:', webengine_path)
        
        # Альтернативный путь
        print('Альтернативный путь:', QWebEngineProfile.defaultProfile().persistentStoragePath())
        
        # Проверка существования
        print('Файл существует:', os.path.exists(webengine_path))
        "
        Write-Output $output
        
        # Дополнительная проверка
        $path = $output | Select-String -Pattern 'Основной путь: (.*)' | ForEach-Object { $_.Matches.Groups[1].Value }
        if (Test-Path $path) {
            Write-Output "Файл найден: $path"
            Get-Item $path | Format-List *
        } else {
            Write-Output "Файл не найден! Поиск по системе..."
            Get-ChildItem -Path $env:pythonLocation -Recurse -Filter "qtwebengineprocess.exe" -ErrorAction SilentlyContinue | Select-Object FullName
        }
